apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::188481987194:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AVAXFHC3NACO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::188481987194:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-02T21:16:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2224"
  uid: e2a37709-b2e5-4c64-9d59-75408e57ecde
