apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::188481987194:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MIYUWVP76X98
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam:188481987194:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-02T16:03:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "12291"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a0acda3e-906b-4b7a-9f00-d46dac2e9d5c
