apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::188481987194:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MMXOD35XXF0G
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::188481987194:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-06T18:23:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2138"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1becf53f-9aed-412f-a2f8-9169a4418b65
